name: 'setup-yq'
description: 'Install yq parser'
author: 'freenet'
inputs:
  version:
    required: true
    description: 'Version of yq'
    default: 'v4.46.1'
runs:
  using: 'node20'
  main: 'dist/index.js'
